--CREACION DE LA BASE DE DATOS
IF NOT EXISTS (SELECT *FROM sys.databases WHERE name = 'RESERVATIONS')
        CREATE DATABASE [RESERVATIONS]            
GO

--MONTAR BASE DE DATOS
USE RESERVATIONS
GO

--TABLAS

--CATEGORIA
IF NOT EXISTS(SELECT * FROM sys.tables WHERE name='CATEGORIA')
CREATE TABLE CATEGORIA (
ID      	    TINYINT IDENTITY (1,1) PRIMARY KEY,
NOMBRE			VARCHAR(20) NOT NULL
)
GO

--MENU
IF NOT EXISTS(SELECT * FROM sys.tables WHERE name='MENU')
CREATE TABLE MENU (
ID  		INT IDENTITY (1,1) PRIMARY KEY,
NOMBRE		VARCHAR(50) NOT NULL,
PRECIO		SMALLMONEY NOT NULL,
CATEGORIA   TINYINT NOT NULL

FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA
)
GO

--HORARIO
IF NOT EXISTS(SELECT * FROM sys.tables WHERE name='HORARIO')
CREATE TABLE HORARIO (
ID      		TINYINT IDENTITY (1,1) PRIMARY KEY,
DESCRIPCION		VARCHAR(7) NOT NULL
)
GO

--RESERVACION
IF NOT EXISTS(SELECT * FROM sys.tables WHERE name='RESERVATION')
CREATE TABLE RESERVATION (
ID          INT IDENTITY (1,1) PRIMARY KEY,
NOMBRES		VARCHAR(50) NOT NULL,
APELLIDOS	VARCHAR(50) NOT NULL,
CELULAR     CHAR(9) NOT NULL,
CORREO      VARCHAR(50) NOT NULL,
HORA        TINYINT NOT NULL,
MESA        TINYINT NOT NULL, 
CODIGO      CHAR(6) NOT NULL,

CONSTRAINT RESERVA_UNICA UNIQUE (hora, mesa),

FOREIGN KEY (HORA) REFERENCES HORARIO
)
GO

--PROCEDIMIENTOS ALMACENADOS

--CONSULTAR MENU
CREATE OR ALTER PROCEDURE LISTAR_MENU
AS
SELECT NOMBRE, PRECIO, CATEGORIA FROM MENU
GO

--VERIFICAR CORREO
CREATE OR ALTER PROCEDURE EMAIL_VALIDATION
    @CORREO VARCHAR(50)
AS
BEGIN
DECLARE @SUCCESS BIT
	IF NOT EXISTS (SELECT ID FROM RESERVATION WHERE @CORREO = CORREO)
	BEGIN
		SET @SUCCESS = 1
	END
	ELSE
	BEGIN
		SET @SUCCESS = 0		
	END
SELECT @SUCCESS AS RESPONSE
END
GO

--HACER RESERVACION
CREATE OR ALTER PROCEDURE MAKE_RESERVATION
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR(50),
@CELULAR CHAR(9),
@CORREO VARCHAR(50),
@HORA TINYINT,
@CODIGO CHAR(6)
AS
BEGIN
DECLARE @NROMESA TINYINT, @SUCCESS BIT, @TOTALMESAS TINYINT
--ASIGNAR TOTAL DE MESAS
SET @TOTALMESAS = 6
--BUSCA MESA DISPONIBLE PARA EL HORARIO SOLICITADO
 SELECT @NROMESA = COALESCE(MAX(mesa), 0) + 1 --COALESCE DETECTA SI HAY NULL, SI LO HAY DEVUELVE 0, 0 ES EL VALOR DE RESPALDO
    FROM RESERVATION
    WHERE hora = @HORA;
--AL ENCONTRAR MESA
IF @NROMESA <= @TOTALMESAS
    BEGIN
        INSERT INTO RESERVATION (NOMBRES, APELLIDOS, CELULAR, CORREO, HORA, MESA, CODIGO)
        VALUES (@NOMBRE, @APELLIDO, @CELULAR, @CORREO, @HORA, @NROMESA, @CODIGO);
        SET @SUCCESS = 1;
    END
--AL NO ENCONTRAR MESA
 ELSE
    BEGIN
        SET @SUCCESS = 0;
    END
SELECT @SUCCESS AS RESPONSE
END
GO

--LISTAR HORARIOS
CREATE OR ALTER PROCEDURE LISTAR_HORARIOS
AS
SELECT * FROM HORARIO
GO

--BUSCAR RESERVACION
CREATE OR ALTER PROCEDURE SEARCH_RESERVATION
    @CODIGO NVARCHAR(50)
AS
BEGIN
    SELECT 
        (NOMBRES + ' ' + APELLIDOS) AS Cliente,
        HORA,
        MESA
    FROM RESERVATION
    WHERE CODIGO = @CODIGO
END
GO

--ELIMINAR RESERVACION
CREATE OR ALTER PROCEDURE DELETE_RESERVATION
    @CODE CHAR(6)
AS
BEGIN
DECLARE @SUCCESS BIT
DECLARE @CORREO NVARCHAR(50)
	IF NOT EXISTS (SELECT ID FROM RESERVATION WHERE @CODE = CODIGO)
	BEGIN
		SET @SUCCESS = 0
		SELECT @SUCCESS AS RESPONSE
	END
	ELSE
	BEGIN
        SELECT @CORREO = CORREO FROM RESERVATION WHERE CODIGO = @CODE
        DELETE FROM RESERVATION WHERE CODIGO = @CODE
        SET @SUCCESS = 1
        SELECT @SUCCESS AS RESPONSE, @CORREO AS CORREO
	END
END
GO

--INSERCCIONES

--CATEGORIAS
INSERT INTO CATEGORIA (NOMBRE) VALUES ('BEBIDAS FRIAS')
INSERT INTO CATEGORIA (NOMBRE) VALUES ('BEBIDAS CALIENTES')
INSERT INTO CATEGORIA (NOMBRE) VALUES ('POSTRES')
INSERT INTO CATEGORIA (NOMBRE) VALUES ('SANDWICHES')

--HORARIO
INSERT INTO HORARIO (DESCRIPCION) VALUES ('4-5p.m')
INSERT INTO HORARIO (DESCRIPCION) VALUES ('5-6p.m')
INSERT INTO HORARIO (DESCRIPCION) VALUES ('6-7p.m')
INSERT INTO HORARIO (DESCRIPCION) VALUES ('7-8p.m')
INSERT INTO HORARIO (DESCRIPCION) VALUES ('8-9p.m')
INSERT INTO HORARIO (DESCRIPCION) VALUES ('9-10p.m')

--MENU
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo de fresa',15.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('cafe americano',13.70,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('pye de manzana',9.90,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('tartaleta de fresa',11.20,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo de naranja',15.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('capuccino regular',16.30,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('capuccino moka',17.30,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('capuccino vainilla',16.65,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('cafe latte',14.80,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('cafe expreso',15.00,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo surtido',14.00,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('limonada frozen',13.60,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('fresa frozen',14.60,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('frapuccino de crema de caramelo',18.25,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('frapuccino de menta y moka',19.10,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('frapuccino de crema de fresas',20.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('tres leches',12.50,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('galletas de avena',8.50,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('sandwich de queso',7.30,4)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('sandwich de jamon',7.30,4)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('sandwich de jamon y queso',9.30,4)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('mixto extra cheese',9.30,4)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('mixto especial',9.90,4)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('triple clasico',8.20,4)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('sandwich hawaino',8.40,4)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('sandwich especial de pollo',8.60,4)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo de mango',15.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo de piña',15.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo de platano con fresa',16.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo de mango con lucuma',16.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo de piña con platano',16.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo de melon con papaya',16.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('jugo de platano con papaya',16.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('mango frozen',17.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('menta frozen',17.50,1)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('chocolate aleman',19.50,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('cafe italiano',22.50,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('selva negra',10.60,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('pye de limon',11.60,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('red velvet',12.60,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('cheescake de fresa',13.60,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('pionono de chocolate',14.80,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('torta princesa',20.80,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('torta helada',11.70,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('cafe colombiano',19.70,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('queque ingles',12.50,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('mil hojas',11.20,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('mil hojas de fresa',12.20,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('chocolate caliente',15.20,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('te de menta',10.40,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('te de manzanilla',10.40,2)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('alfajor',6.60,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('gelatina de menta',5.10,3)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('sandwich de atun',6.90,4)
INSERT INTO MENU (NOMBRE,PRECIO,CATEGORIA) VALUES ('triple vegetariano',8.90,4)

--RESERVACIONES

EXEC MAKE_RESERVATION 'Jeremías', 'Lopez', '992987159', 'jeremi@hotmail.com',1, 'AGC163'
GO

EXEC MAKE_RESERVATION 'Astolfo', 'Linares', '993577159', 'asLin@outlook.com',1, 'Y7C163'
GO

EXEC MAKE_RESERVATION 'Mariana', 'Tavara', '993572659', 'MariTA@gmail.com',1, '05p163'
GO

EXEC MAKE_RESERVATION 'Raquel', 'Bosques', '990582659', 'RaBos@yahoo.com',1, '0iu863'
GO

EXEC MAKE_RESERVATION 'Paula', 'Bermudez', '990535959', 'PauBer@zooho.com',1, 'L05u62'
GO


--PRUEBAS

EXEC EMAIL_VALIDATION 'PauBer@zooho.com'
GO

SELECT * FROM RESERVATION
GO	

EXEC SEARCH_RESERVATION '05p163'
GO

DELETE FROM RESERVATION
GO